version: '3.9'

services:
  mongo:
    image: mongo
    container_name: chat-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: Chat.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDB: mongodb://admin:adminpass@mongo:27017
    depends_on:
      - mongo

  ui:
    build:
      context: ./Chat.UI.React
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  mongo-data:
